# Generated by Django 6.0.3 on 2026-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('rooms', 'Rooms'), ('dining', 'Dining'), ('spa', 'Spa'), ('pool', 'Pool'), ('exterior', 'Exterior'), ('amenities', 'Amenities')], default='rooms', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
