# Generated by Django 6.0.3 on 2026-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_testimonial_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('rooms', 'Rooms'), ('restaurants', 'Restaurants'), ('rooftopbar', 'Rooftopbar'), ('receptionist', 'Receptionist'), ('stairs', 'Stairs'), ('hallway', 'Hallway')], default='rooms', max_length=50),
        ),
    ]
